describe("review_build_checklist", {
  it("includes base checklist for any files", {
    result <- review_build_checklist("README.md", "jinx")
    expect_true(grepl("Review Checklist", result, fixed = TRUE))
    expect_true(grepl("sensitive information", result, fixed = TRUE))
  })

  it("adds JSON section for .json files", {
    result <- review_build_checklist("data/entry.json", "jinx")
    expect_true(grepl("JSON files", result, fixed = TRUE))
    expect_true(grepl("well-formatted", result, fixed = TRUE))
  })

  it("adds R code section for .R files", {
    result <- review_build_checklist("R/foo.R", "jinx")
    expect_true(grepl("R code", result, fixed = TRUE))
    expect_true(grepl("roxygen2", result, fixed = TRUE))
  })

  it("adds workflow section for workflow files", {
    result <- review_build_checklist(".github/workflows/ci.yml", "jinx")
    expect_true(grepl("GitHub Actions", result, fixed = TRUE))
    expect_true(grepl("pinned versions", result, fixed = TRUE))
  })

  it("adds content section for markdown files", {
    result <- review_build_checklist("content/blog/post.md", "jinx")
    expect_true(grepl("Content", result, fixed = TRUE))
    expect_true(grepl("alt text", result, fixed = TRUE))
  })

  it("adds data section with directory-specific items", {
    result <- review_build_checklist("data/entry.json", "directory")
    expect_true(grepl("Data", result, fixed = TRUE))
    expect_true(grepl("Social media handles", result, fixed = TRUE))
  })

  it("adds data section without directory items for other repos", {
    result <- review_build_checklist("data/entry.json", "jinx")
    expect_true(grepl("Data", result, fixed = TRUE))
    expect_false(grepl("Social media handles", result, fixed = TRUE))
  })

  it("handles multiple file types", {
    files <- c("R/foo.R", "data/bar.json", ".github/workflows/ci.yml")
    result <- review_build_checklist(files, "jinx")
    expect_true(grepl("R code", result, fixed = TRUE))
    expect_true(grepl("JSON files", result, fixed = TRUE))
    expect_true(grepl("GitHub Actions", result, fixed = TRUE))
  })

  it("includes jinx signature", {
    result <- review_build_checklist("foo.txt", "jinx")
    expect_true(grepl("Generated by jinx", result, fixed = TRUE))
  })
})

describe("review_check_naming", {
  it("accepts valid lowercase json filenames", {
    result <- review_check_naming("data/buenos-aires.json", "directory")
    expect_true(result$valid[1])
  })

  it("rejects uppercase in json filenames", {
    result <- review_check_naming("data/BuenosAires.json", "directory")
    expect_false(result$valid[1])
    expect_true(grepl("lowercase", result$reason[1], fixed = TRUE))
  })

  it("rejects special characters in json filenames", {
    result <- review_check_naming("data/buenos aires.json", "directory")
    expect_false(result$valid[1])
    expect_true(grepl("invalid characters", result$reason[1], fixed = TRUE))
  })

  it("rejects leading hyphen", {
    result <- review_check_naming("data/-buenos.json", "directory")
    expect_false(result$valid[1])
    expect_true(grepl("hyphen", result$reason[1], fixed = TRUE))
  })

  it("rejects trailing hyphen", {
    result <- review_check_naming("data/buenos-.json", "directory")
    expect_false(result$valid[1])
    expect_true(grepl("hyphen", result$reason[1], fixed = TRUE))
  })

  it("skips non-json files", {
    result <- review_check_naming("R/BadName.R", "directory")
    expect_true(result$valid[1])
  })

  it("only checks data/blogs/contact paths", {
    result <- review_check_naming("src/BadName.json", "directory")
    expect_true(result$valid[1])
  })

  it("checks blogs path", {
    result <- review_check_naming("blogs/Bad Name.json", "directory")
    expect_false(result$valid[1])
  })

  it("reports multiple reasons", {
    result <- review_check_naming("data/-Bad Name.json", "directory")
    expect_false(result$valid[1])
    expect_true(grepl(";", result$reason[1], fixed = TRUE))
  })
})

describe("review_format_violations", {
  it("formats violations as markdown table", {
    violations <- data.frame(
      filename = c("data/Bad.json", "data/no good.json"),
      valid = c(FALSE, FALSE),
      reason = c("must be lowercase", "invalid characters"),
      stringsAsFactors = FALSE
    )
    result <- review_format_violations(violations)
    expect_true(grepl("Naming Convention", result, fixed = TRUE))
    expect_true(grepl("Bad.json", result))
    expect_true(grepl("no good.json", result))
    expect_true(grepl("Generated by jinx", result, fixed = TRUE))
  })
})
