describe("is_bot", {
  it("detects [bot] suffix", {
    expect_true(is_bot("dependabot[bot]"))
    expect_true(is_bot("renovate[bot]"))
  })

  it("detects known bot names", {
    expect_true(is_bot("github-actions"))
    expect_true(is_bot("dependabot"))
  })

  it("rejects normal users", {
    expect_false(is_bot("octocat"))
    expect_false(is_bot("drmowinckels"))
  })
})

describe("welcome_first_time_message", {
  it("generates PR welcome message", {
    msg <- welcome_first_time_message("octocat", "jinx", is_pr = TRUE)
    expect_true(grepl("Welcome to \\*\\*jinx\\*\\*", msg))
    expect_true(grepl("@octocat", msg))
    expect_true(grepl("pull request", msg))
    expect_true(grepl("Generated by jinx", msg))
  })

  it("generates issue welcome message", {
    msg <- welcome_first_time_message("octocat", "jinx", is_pr = FALSE)
    expect_true(grepl("issue", msg))
    expect_false(grepl("pull request", msg))
  })
})

describe("welcome_returning_message", {
  it("generates returning PR message", {
    msg <- welcome_returning_message("octocat", is_pr = TRUE)
    expect_true(grepl("@octocat", msg))
    expect_true(grepl("pull request", msg))
  })

  it("generates returning issue message", {
    msg <- welcome_returning_message("octocat", is_pr = FALSE)
    expect_true(grepl("issue", msg))
  })
})

describe("format_contributors_table", {
  it("formats as markdown table", {
    df <- data.frame(
      login = c("alice", "bob"),
      contributions = c(10L, 5L),
      avatar_url = c("https://example.com/a.png", "https://example.com/b.png"),
      profile_url = c("https://github.com/alice", "https://github.com/bob"),
      stringsAsFactors = FALSE
    )
    result <- format_contributors_table(df)
    expect_true(grepl("\\| Avatar \\| Contributor", result))
    expect_true(grepl("@alice", result))
    expect_true(grepl("@bob", result))
    expect_true(grepl("10", result))
  })
})

describe("format_contributors_grid", {
  it("formats as image grid", {
    df <- data.frame(
      login = c("alice", "bob"),
      contributions = c(10L, 5L),
      avatar_url = c("https://example.com/a.png", "https://example.com/b.png"),
      profile_url = c("https://github.com/alice", "https://github.com/bob"),
      stringsAsFactors = FALSE
    )
    result <- format_contributors_grid(df, cols = 7)
    expect_true(grepl("alice", result))
    expect_true(grepl("bob", result))
    expect_true(grepl("<img", result))
  })

  it("wraps rows at specified columns", {
    df <- data.frame(
      login = paste0("user", 1:5),
      contributions = rep(1L, 5),
      avatar_url = rep("https://example.com/a.png", 5),
      profile_url = rep("https://github.com/user", 5),
      stringsAsFactors = FALSE
    )
    result <- format_contributors_grid(df, cols = 3)
    lines <- strsplit(result, "\n\n")[[1]]
    expect_equal(length(lines), 2)
  })
})

describe("format_contributors", {
  it("returns empty message for empty data", {
    df <- data.frame(
      login = character(0),
      contributions = integer(0),
      avatar_url = character(0),
      profile_url = character(0),
      stringsAsFactors = FALSE
    )
    expect_equal(format_contributors(df), "No contributors yet.")
  })

  it("dispatches to table format", {
    df <- data.frame(
      login = "alice",
      contributions = 1L,
      avatar_url = "url",
      profile_url = "url",
      stringsAsFactors = FALSE
    )
    result <- format_contributors(df, format = "table")
    expect_true(grepl("Avatar", result))
  })

  it("dispatches to grid format", {
    df <- data.frame(
      login = "alice",
      contributions = 1L,
      avatar_url = "url",
      profile_url = "url",
      stringsAsFactors = FALSE
    )
    result <- format_contributors(df, format = "grid")
    expect_true(grepl("<img", result))
  })
})
