describe("is_bot", {
  it("detects [bot] suffix", {
    expect_true(is_bot("dependabot[bot]"))
    expect_true(is_bot("renovate[bot]"))
  })

  it("detects known bot names", {
    expect_true(is_bot("github-actions"))
    expect_true(is_bot("dependabot"))
  })

  it("rejects normal users", {
    expect_false(is_bot("octocat"))
    expect_false(is_bot("drmowinckels"))
  })
})

describe("gh_welcome_message_first_time", {
  it("generates PR welcome message", {
    msg <- gh_welcome_message_first_time("octocat", "jinx", is_pr = TRUE)
    expect_true(grepl("Welcome to **jinx**", msg, fixed = TRUE))
    expect_true(grepl("@octocat", msg, fixed = TRUE))
    expect_true(grepl("pull request", msg, fixed = TRUE))
    expect_true(grepl("Generated by jinx", msg, fixed = TRUE))
  })

  it("generates issue welcome message", {
    msg <- gh_welcome_message_first_time("octocat", "jinx", is_pr = FALSE)
    expect_true(grepl("issue", msg, fixed = TRUE))
    expect_false(grepl("pull request", msg, fixed = TRUE))
  })
})

describe("gh_welcome_message_returning", {
  it("generates returning PR message", {
    msg <- gh_welcome_message_returning("octocat", is_pr = TRUE)
    expect_true(grepl("@octocat", msg, fixed = TRUE))
    expect_true(grepl("pull request", msg, fixed = TRUE))
  })

  it("generates returning issue message", {
    msg <- gh_welcome_message_returning("octocat", is_pr = FALSE)
    expect_true(grepl("issue", msg, fixed = TRUE))
  })
})

describe("gh_greet_contributor", {
  it("delegates to gh_welcome_contributor with is_pr = TRUE", {
    called <- list()
    local_mocked_bindings(
      gh_welcome_contributor = function(
        owner,
        repo,
        number,
        author,
        is_pr,
        org,
        extra_message
      ) {
        called <<- list(
          owner = owner,
          repo = repo,
          number = number,
          author = author,
          is_pr = is_pr,
          org = org,
          extra_message = extra_message
        )
        "url"
      }
    )
    gh_greet_contributor("o", "r", 1L, "ada", org = "rladies")
    expect_identical(called$is_pr, TRUE)
    expect_identical(called$author, "ada")
    expect_identical(called$org, "rladies")
  })

  it("forwards extra_message", {
    received <- NULL
    local_mocked_bindings(
      gh_welcome_contributor = function(..., extra_message) {
        received <<- extra_message
        "url"
      }
    )
    gh_greet_contributor(
      "o",
      "r",
      1L,
      "ada",
      extra_message = "please add yourself to .zenodo.json"
    )
    expect_identical(received, "please add yourself to .zenodo.json")
  })
})

describe("gh_welcome_message_with_extra", {
  it("returns the base message untouched when extra is empty", {
    base <- "hello\n\n_Generated by jinx_"
    expect_identical(gh_welcome_message_with_extra(base, NULL), base)
    expect_identical(gh_welcome_message_with_extra(base, ""), base)
    expect_identical(gh_welcome_message_with_extra(base, "   "), base)
  })

  it("appends extra and keeps the jinx signature last", {
    base <- "hello @octocat!\n\n_Generated by jinx_"
    result <- gh_welcome_message_with_extra(
      base,
      "remember to add yourself to .zenodo.json"
    )
    expect_true(grepl("hello @octocat!", result, fixed = TRUE))
    expect_true(grepl(".zenodo.json", result, fixed = TRUE))
    expect_true(endsWith(result, "_Generated by jinx_"))
    expect_equal(
      length(gregexpr("_Generated by jinx_", result, fixed = TRUE)[[1]]),
      1L
    )
  })
})

describe("gh_branch_upsert", {
  it("creates the branch via POST when it doesn't exist", {
    calls <- list()
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        calls[[length(calls) + 1]] <<- endpoint
        if (grepl("^GET .*/git/ref/heads", endpoint)) {
          return(list(object = list(sha = "basesha")))
        }
        if (grepl("^POST .*/git/refs$", endpoint)) {
          return(list(object = list(sha = "basesha")))
        }
        list()
      },
      .package = "gh"
    )
    sha <- gh_branch_upsert("rladies", "directory", "jinx/x")
    expect_identical(sha, "basesha")
    expect_true(any(grepl("^POST .*/git/refs$", calls)))
    expect_false(any(grepl("^PATCH", calls)))
  })

  it("force-updates an existing branch when force is TRUE", {
    calls <- list()
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        calls[[length(calls) + 1]] <<- endpoint
        if (grepl("^GET .*/git/ref/heads", endpoint)) {
          return(list(object = list(sha = "basesha")))
        }
        if (grepl("^POST .*/git/refs$", endpoint)) {
          stop("branch exists")
        }
        list()
      },
      .package = "gh"
    )
    gh_branch_upsert("rladies", "directory", "jinx/x", force = TRUE)
    expect_true(any(grepl("^PATCH .*/git/refs/heads", calls)))
  })

  it("leaves an existing branch alone when force is FALSE", {
    calls <- list()
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        calls[[length(calls) + 1]] <<- endpoint
        if (grepl("^GET .*/git/ref/heads", endpoint)) {
          return(list(object = list(sha = "basesha")))
        }
        if (grepl("^POST .*/git/refs$", endpoint)) {
          stop("branch exists")
        }
        list()
      },
      .package = "gh"
    )
    gh_branch_upsert("rladies", "directory", "chapter/x", force = FALSE)
    expect_false(any(grepl("^PATCH", calls)))
  })
})

describe("gh_open_or_update_pr", {
  it("returns the existing open PR's URL if one is already open", {
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        if (grepl("^GET .*/pulls", endpoint)) {
          return(list(list(html_url = "https://github.com/x/y/pull/9")))
        }
        stop("should not POST")
      },
      .package = "gh"
    )
    url <- gh_open_or_update_pr(
      "rladies",
      "directory",
      "jinx/x",
      title = "t",
      body = "b"
    )
    expect_identical(url, "https://github.com/x/y/pull/9")
  })

  it("opens a new PR when none is open", {
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        if (grepl("^GET .*/pulls", endpoint)) {
          return(list())
        }
        if (grepl("^POST .*/pulls", endpoint)) {
          return(list(html_url = "https://github.com/x/y/pull/10"))
        }
        list()
      },
      .package = "gh"
    )
    url <- gh_open_or_update_pr(
      "rladies",
      "directory",
      "jinx/x",
      title = "t",
      body = "b"
    )
    expect_identical(url, "https://github.com/x/y/pull/10")
  })
})

describe("gh_coauthor_logins", {
  it("extracts logins from noreply co-author trailers", {
    message <- paste(
      "feat: something",
      "",
      "Co-authored-by: Ada Lovelace <123+ada@users.noreply.github.com>",
      "Co-authored-by: Grace <grace@users.noreply.github.com>",
      sep = "\n"
    )
    expect_identical(gh_coauthor_logins(message), c("ada", "grace"))
  })

  it("ignores trailers without a resolvable GitHub email", {
    message <- paste(
      "fix: thing",
      "Co-authored-by: Someone <someone@example.com>",
      "Co-authored-by: No Email Here",
      sep = "\n"
    )
    expect_identical(gh_coauthor_logins(message), character(0))
  })

  it("returns nothing for a plain message", {
    expect_identical(gh_coauthor_logins("docs: tidy up"), character(0))
  })

  it("rejects a trailer that is not shaped like a login", {
    message <- paste(
      "feat: x",
      paste0(
        "Co-authored-by: X <1+evil](https://evil.example) @rladies/global",
        "@users.noreply.github.com>"
      ),
      sep = "\n"
    )
    expect_match(message, "\nCo-authored-by:")
    expect_identical(gh_coauthor_logins(message), character(0))
  })
})

describe("is_valid_login", {
  it("accepts GitHub logins", {
    expect_true(is_valid_login("ada"))
    expect_true(is_valid_login("R-Ladies-Oslo"))
    expect_true(is_valid_login("a1"))
  })

  it("rejects anything that could become markdown or a team mention", {
    expect_false(is_valid_login("rladies/global"))
    expect_false(is_valid_login("evil](https://evil.example)"))
    expect_false(is_valid_login("ada lovelace"))
    expect_false(is_valid_login(""))
    expect_false(is_valid_login("-ada"))
    expect_false(is_valid_login("ada--lovelace"))
    expect_false(is_valid_login(strrep("a", 40)))
  })
})

describe("gh_and_list", {
  it("returns a single item unchanged", {
    expect_identical(gh_and_list("@ada"), "@ada")
  })

  it("joins two items with and", {
    expect_identical(gh_and_list(c("@ada", "@grace")), "@ada and @grace")
  })

  it("joins three items with commas and a final and", {
    expect_identical(
      gh_and_list(c("@ada", "@grace", "@hedy")),
      "@ada, @grace and @hedy"
    )
  })

  it("returns an empty string for nothing", {
    expect_identical(gh_and_list(character(0)), "")
  })
})

describe("gh_mention_list", {
  it("prefixes logins with @", {
    expect_identical(gh_mention_list(c("ada", "grace")), "@ada and @grace")
  })
})

describe("gh_pr_helpers", {
  pr_fetch_stub <- function(endpoint, ...) {
    if (grepl("commits", endpoint)) {
      return(list(
        list(
          author = list(login = "ada"),
          commit = list(
            message = paste(
              "feat: thing",
              "Co-authored-by: Grace <9+grace@users.noreply.github.com>",
              sep = "\n"
            )
          )
        ),
        list(
          author = list(login = "hedy"),
          commit = list(message = "fix: thing")
        )
      ))
    }
    if (grepl("reviews", endpoint)) {
      return(list(
        list(user = list(login = "marie"), state = "APPROVED"),
        list(user = list(login = "rosalind"), state = "PENDING"),
        list(user = list(login = "github-actions"), state = "COMMENTED")
      ))
    }
    list(
      list(user = list(login = "lise")),
      list(user = list(login = "marie")),
      list(user = list(login = "copilot[bot]"))
    )
  }

  it("collects co-authors, reviewers and commenters", {
    local_mocked_bindings(gh_api_fetch = pr_fetch_stub)
    helpers <- gh_pr_helpers("rladies", "jinx", 1L, "ada")
    expect_identical(helpers$login, c("grace", "hedy", "marie", "lise"))
    expect_identical(
      helpers$role,
      c("co-author", "co-author", "reviewer", "commenter")
    )
  })

  it("excludes the author, bots and pending reviews", {
    local_mocked_bindings(gh_api_fetch = pr_fetch_stub)
    helpers <- gh_pr_helpers("rladies", "jinx", 1L, "ada")
    expect_false("ada" %in% helpers$login)
    expect_false("rosalind" %in% helpers$login)
    expect_false(any(grepl("bot|github-actions", helpers$login)))
  })

  it("keeps the first role a person appears in", {
    local_mocked_bindings(gh_api_fetch = pr_fetch_stub)
    helpers <- gh_pr_helpers("rladies", "jinx", 1L, "ada")
    expect_identical(helpers$role[helpers$login == "marie"], "reviewer")
  })

  it("returns no rows when nothing is found", {
    local_mocked_bindings(gh_api_fetch = function(endpoint, ...) list())
    expect_identical(nrow(gh_pr_helpers("rladies", "jinx", 1L, "ada")), 0L)
  })
})

describe("gh_api_fetch", {
  it("wraps a single object response in a list", {
    local_mocked_bindings(
      gh = function(...) list(login = "ada"),
      .package = "gh"
    )
    expect_identical(gh_api_fetch("GET /x"), list(list(login = "ada")))
  })

  it("returns an empty list and warns when the call fails", {
    local_mocked_bindings(
      gh = function(...) stop("404"),
      .package = "gh"
    )
    expect_message(
      result <- gh_api_fetch("GET /x"),
      "Could not fetch"
    )
    expect_identical(result, list())
  })
})

describe("gh_thank_helpers_line", {
  it("returns nothing when there are no helpers", {
    empty <- data.frame(
      login = character(0),
      role = character(0),
      stringsAsFactors = FALSE
    )
    expect_identical(gh_thank_helpers_line(empty), character(0))
  })

  it("groups people by what they did", {
    helpers <- data.frame(
      login = c("grace", "marie", "lise", "hedy"),
      role = c("co-author", "reviewer", "commenter", "reviewer"),
      stringsAsFactors = FALSE
    )
    line <- gh_thank_helpers_line(helpers)
    expect_true(grepl("@grace for co-authoring", line, fixed = TRUE))
    expect_true(grepl("@marie and @hedy for reviewing", line, fixed = TRUE))
    expect_true(
      grepl("@lise for joining the discussion", line, fixed = TRUE)
    )
  })
})

describe("gh_thank_message", {
  no_helpers <- data.frame(
    login = character(0),
    role = character(0),
    stringsAsFactors = FALSE
  )

  it("congratulates a first-time contributor", {
    msg <- gh_thank_message("ada", "jinx", TRUE, no_helpers)
    expect_true(grepl("first contribution to **jinx**", msg, fixed = TRUE))
    expect_true(grepl("_Generated by jinx_", msg, fixed = TRUE))
    expect_false(grepl("Thanks also", msg, fixed = TRUE))
  })

  it("thanks a returning contributor", {
    msg <- gh_thank_message("ada", "jinx", FALSE, no_helpers)
    expect_true(grepl(
      "Thank you for your contribution, @ada!",
      msg,
      fixed = TRUE
    ))
  })

  it("credits helpers before the signature", {
    helpers <- data.frame(
      login = "marie",
      role = "reviewer",
      stringsAsFactors = FALSE
    )
    msg <- gh_thank_message("ada", "jinx", FALSE, helpers)
    expect_lt(
      regexpr("Thanks also", msg, fixed = TRUE),
      regexpr("_Generated by jinx_", msg, fixed = TRUE)
    )
  })
})

describe("gh_thank_contributor", {
  it("posts a comment crediting everyone who helped", {
    posted <- NULL
    local_mocked_bindings(
      is_first_time_contributor = function(...) FALSE,
      gh_pr_helpers = function(...) {
        data.frame(
          login = "marie",
          role = "reviewer",
          stringsAsFactors = FALSE
        )
      }
    )
    local_mocked_bindings(
      gh = function(endpoint, ..., body) {
        posted <<- body
        list(html_url = "https://example.com/comment")
      },
      .package = "gh"
    )
    url <- gh_thank_contributor("rladies", "jinx", 1L, "ada")
    expect_identical(url, "https://example.com/comment")
    expect_true(grepl("@ada", posted, fixed = TRUE))
    expect_true(grepl("@marie for reviewing", posted, fixed = TRUE))
  })

  it("does nothing for bot authors", {
    expect_null(gh_thank_contributor("rladies", "jinx", 1L, "dependabot[bot]"))
  })
})

describe("gh_issue_helpers", {
  issue_fetch_stub <- function(endpoint, ...) {
    if (grepl("issues/\\{issue_number\\}$", endpoint)) {
      return(list(list(
        assignees = list(
          list(login = "marie"),
          list(login = "hedy")
        )
      )))
    }
    list(
      list(user = list(login = "lise")),
      list(user = list(login = "marie")),
      list(user = list(login = "ada")),
      list(user = list(login = "github-actions"))
    )
  }

  it("credits assignees and commenters", {
    local_mocked_bindings(gh_api_fetch = issue_fetch_stub)
    helpers <- gh_issue_helpers("rladies", "jinx", 1L, "ada")
    expect_identical(helpers$login, c("marie", "hedy", "lise"))
    expect_identical(helpers$role, c("assignee", "assignee", "commenter"))
  })

  it("does not ask for review comments on an issue", {
    seen <- character(0)
    local_mocked_bindings(
      gh_api_fetch = function(endpoint, ...) {
        seen <<- c(seen, endpoint)
        issue_fetch_stub(endpoint, ...)
      }
    )
    gh_issue_helpers("rladies", "jinx", 1L, "ada")
    expect_false(any(grepl("pulls", seen)))
  })

  it("copes with an issue nobody was assigned", {
    local_mocked_bindings(
      gh_api_fetch = function(endpoint, ...) {
        if (grepl("issues/\\{issue_number\\}$", endpoint)) {
          return(list(list(assignees = list())))
        }
        list(list(user = list(login = "lise")))
      }
    )
    helpers <- gh_issue_helpers("rladies", "jinx", 1L, "ada")
    expect_identical(helpers$login, "lise")
  })
})

describe("gh_thank_message for issues", {
  no_helpers <- data.frame(
    login = character(0),
    role = character(0),
    stringsAsFactors = FALSE
  )

  it("welcomes a first-time issue reporter", {
    msg <- gh_thank_message("ada", "jinx", TRUE, no_helpers, is_pr = FALSE)
    expect_true(grepl("first issue in **jinx**", msg, fixed = TRUE))
    expect_false(grepl("contribution", msg, fixed = TRUE))
  })

  it("thanks a returning issue reporter", {
    msg <- gh_thank_message("ada", "jinx", FALSE, no_helpers, is_pr = FALSE)
    expect_true(grepl("Thank you for raising this, @ada!", msg, fixed = TRUE))
  })
})

describe("gh_thank_issue_contributors", {
  it("posts a comment crediting the reporter and the helpers", {
    posted <- NULL
    local_mocked_bindings(
      is_first_time_contributor = function(...) FALSE,
      gh_issue_helpers = function(...) {
        data.frame(
          login = "marie",
          role = "assignee",
          stringsAsFactors = FALSE
        )
      }
    )
    local_mocked_bindings(
      gh = function(endpoint, ..., body) {
        posted <<- body
        list(html_url = "https://example.com/comment")
      },
      .package = "gh"
    )
    url <- gh_thank_issue_contributors("rladies", "jinx", 7L, "ada")
    expect_identical(url, "https://example.com/comment")
    expect_true(grepl("Thank you for raising this, @ada", posted, fixed = TRUE))
    expect_true(grepl("@marie for picking this up", posted, fixed = TRUE))
  })

  it("checks first-time status against issues, not PRs", {
    seen <- NULL
    local_mocked_bindings(
      is_first_time_contributor = function(owner, repo, author, is_pr) {
        seen <<- is_pr
        FALSE
      },
      gh_issue_helpers = function(...) {
        data.frame(
          login = character(0),
          role = character(0),
          stringsAsFactors = FALSE
        )
      }
    )
    local_mocked_bindings(
      gh = function(...) list(html_url = "u"),
      .package = "gh"
    )
    gh_thank_issue_contributors("rladies", "jinx", 7L, "ada")
    expect_false(seen)
  })

  it("does nothing for bot authors", {
    expect_null(
      gh_thank_issue_contributors("rladies", "jinx", 7L, "dependabot[bot]")
    )
  })
})

describe("gh_thankable", {
  frame <- function(login, role, type = "User") {
    data.frame(
      login = login,
      role = role,
      type = type,
      stringsAsFactors = FALSE
    )
  }

  it("drops a bot that has no [bot] suffix, going by its account type", {
    found <- rbind(
      frame("Copilot", "reviewer", "Bot"),
      frame("marie", "reviewer")
    )
    expect_identical(gh_thankable(found, "ada")$login, "marie")
  })

  it("does not mention the author under a different casing", {
    found <- rbind(frame("Ada", "co-author"), frame("marie", "reviewer"))
    expect_identical(gh_thankable(found, "ada")$login, "marie")
  })

  it("thanks one person once across roles that spell them differently", {
    found <- rbind(frame("Marie", "co-author"), frame("marie", "reviewer"))
    thanked <- gh_thankable(found, "ada")
    expect_identical(thanked$login, "Marie")
    expect_identical(thanked$role, "co-author")
  })

  it("drops a ghost user with no login", {
    expect_identical(nrow(gh_thankable(frame("", "commenter"), "ada")), 0L)
  })

  it("keeps a human whose type is missing", {
    found <- data.frame(
      login = "marie",
      role = "reviewer",
      type = NA_character_,
      stringsAsFactors = FALSE
    )
    expect_identical(gh_thankable(found, "ada")$login, "marie")
  })
})

describe("gh_thank_helpers_line wording", {
  helpers <- function(login, role) {
    data.frame(
      login = login,
      role = role,
      stringsAsFactors = FALSE
    )
  }

  it("reads unambiguously with one clause", {
    expect_identical(
      as.character(gh_thank_helpers_line(helpers("marie", "reviewer"))),
      "Thanks also to @marie for reviewing."
    )
  })

  it("separates clauses so the ands cannot run together", {
    line <- gh_thank_helpers_line(
      helpers(
        c("grace", "marie", "hedy"),
        c("co-author", "reviewer", "reviewer")
      )
    )
    expect_identical(
      as.character(line),
      "Thanks also to @grace for co-authoring; @marie and @hedy for reviewing."
    )
  })

  it("keeps every role in order", {
    line <- gh_thank_helpers_line(
      helpers(
        c("grace", "marie", "lise", "rosalind"),
        c("co-author", "reviewer", "assignee", "commenter")
      )
    )
    expect_identical(
      as.character(line),
      paste(
        "Thanks also to @grace for co-authoring; @marie for reviewing;",
        "@lise for picking this up; @rosalind for joining the discussion."
      )
    )
  })
})

describe("gh_coauthor_logins with two addresses", {
  it("takes the first address on the trailer line", {
    message <- paste(
      "feat: x",
      "Co-authored-by: A <1+ada@users.noreply.github.com> <b@example.com>",
      sep = "\n"
    )
    expect_identical(gh_coauthor_logins(message), "ada")
  })
})

describe("gh_pr_helpers endpoints", {
  it("asks for conversation and review comments on a PR", {
    seen <- character(0)
    local_mocked_bindings(
      gh_api_fetch = function(endpoint, ...) {
        seen <<- c(seen, endpoint)
        list()
      }
    )
    gh_pr_helpers("rladies", "jinx", 1L, "ada")
    expect_true(any(grepl("issues/\\{issue_number\\}/comments", seen)))
    expect_true(any(grepl("pulls/\\{pull_number\\}/comments", seen)))
    expect_true(any(grepl("commits", seen)))
    expect_true(any(grepl("reviews", seen)))
  })
})

describe("gh_thank_issue_contributors on a not-planned close", {
  it("thanks without the first-timer congratulation", {
    posted <- NULL
    local_mocked_bindings(
      is_first_time_contributor = function(...) TRUE,
      gh_issue_helpers = function(...) {
        data.frame(
          login = character(0),
          role = character(0),
          stringsAsFactors = FALSE
        )
      }
    )
    local_mocked_bindings(
      gh = function(endpoint, ..., body) {
        posted <<- body
        list(html_url = "u")
      },
      .package = "gh"
    )
    gh_thank_issue_contributors("rladies", "jinx", 7L, "ada", completed = FALSE)
    expect_false(grepl("first issue", posted, fixed = TRUE))
    expect_true(grepl("Thank you for raising this", posted, fixed = TRUE))
  })
})
