describe("is_bot", {
  it("detects [bot] suffix", {
    expect_true(is_bot("dependabot[bot]"))
    expect_true(is_bot("renovate[bot]"))
  })

  it("detects known bot names", {
    expect_true(is_bot("github-actions"))
    expect_true(is_bot("dependabot"))
  })

  it("rejects normal users", {
    expect_false(is_bot("octocat"))
    expect_false(is_bot("drmowinckels"))
  })
})

describe("gh_welcome_message_first_time", {
  it("generates PR welcome message", {
    msg <- gh_welcome_message_first_time("octocat", "jinx", is_pr = TRUE)
    expect_true(grepl("Welcome to **jinx**", msg, fixed = TRUE))
    expect_true(grepl("@octocat", msg, fixed = TRUE))
    expect_true(grepl("pull request", msg, fixed = TRUE))
    expect_true(grepl("Generated by jinx", msg, fixed = TRUE))
  })

  it("generates issue welcome message", {
    msg <- gh_welcome_message_first_time("octocat", "jinx", is_pr = FALSE)
    expect_true(grepl("issue", msg, fixed = TRUE))
    expect_false(grepl("pull request", msg, fixed = TRUE))
  })
})

describe("gh_welcome_message_returning", {
  it("generates returning PR message", {
    msg <- gh_welcome_message_returning("octocat", is_pr = TRUE)
    expect_true(grepl("@octocat", msg, fixed = TRUE))
    expect_true(grepl("pull request", msg, fixed = TRUE))
  })

  it("generates returning issue message", {
    msg <- gh_welcome_message_returning("octocat", is_pr = FALSE)
    expect_true(grepl("issue", msg, fixed = TRUE))
  })
})

describe("gh_greet_contributor", {
  it("delegates to gh_welcome_contributor with is_pr = TRUE", {
    called <- list()
    local_mocked_bindings(
      gh_welcome_contributor = function(
        owner,
        repo,
        number,
        author,
        is_pr,
        org,
        extra_message
      ) {
        called <<- list(
          owner = owner,
          repo = repo,
          number = number,
          author = author,
          is_pr = is_pr,
          org = org,
          extra_message = extra_message
        )
        "url"
      }
    )
    gh_greet_contributor("o", "r", 1L, "ada", org = "rladies")
    expect_identical(called$is_pr, TRUE)
    expect_identical(called$author, "ada")
    expect_identical(called$org, "rladies")
  })

  it("forwards extra_message", {
    received <- NULL
    local_mocked_bindings(
      gh_welcome_contributor = function(..., extra_message) {
        received <<- extra_message
        "url"
      }
    )
    gh_greet_contributor(
      "o",
      "r",
      1L,
      "ada",
      extra_message = "please add yourself to .zenodo.json"
    )
    expect_identical(received, "please add yourself to .zenodo.json")
  })
})

describe("gh_welcome_message_with_extra", {
  it("returns the base message untouched when extra is empty", {
    base <- "hello\n\n_Generated by jinx_"
    expect_identical(gh_welcome_message_with_extra(base, NULL), base)
    expect_identical(gh_welcome_message_with_extra(base, ""), base)
    expect_identical(gh_welcome_message_with_extra(base, "   "), base)
  })

  it("appends extra and keeps the jinx signature last", {
    base <- "hello @octocat!\n\n_Generated by jinx_"
    result <- gh_welcome_message_with_extra(
      base,
      "remember to add yourself to .zenodo.json"
    )
    expect_true(grepl("hello @octocat!", result, fixed = TRUE))
    expect_true(grepl(".zenodo.json", result, fixed = TRUE))
    expect_true(endsWith(result, "_Generated by jinx_"))
    expect_equal(
      length(gregexpr("_Generated by jinx_", result, fixed = TRUE)[[1]]),
      1L
    )
  })
})
