describe("copilot_strip_frontmatter", {
  it("removes a leading YAML frontmatter block", {
    text <- paste(
      "---",
      "name: run-brand-check",
      "description: gate",
      "---",
      "",
      "# Brand check",
      "body here",
      sep = "\n"
    )
    out <- copilot_strip_frontmatter(text)
    expect_true(startsWith(out, "# Brand check"))
    expect_false(grepl("name: run-brand-check", out, fixed = TRUE))
  })

  it("leaves text without frontmatter untouched", {
    text <- "# Title\nbody"
    expect_identical(copilot_strip_frontmatter(text), text)
  })

  it("does not strip when the block is unterminated", {
    text <- "---\nname: x\nno closing fence"
    expect_identical(copilot_strip_frontmatter(text), text)
  })
})

describe("copilot_review_globs", {
  config <- list(
    repos = list(
      default = list(brand = "**", blog = "content/blog/**"),
      website = list(brand = "**", blog = "posts/**")
    )
  )

  it("returns the repo's own entry when present", {
    globs <- copilot_review_globs("website", config)
    expect_identical(globs$blog, "posts/**")
  })

  it("falls back to default for unknown repos", {
    globs <- copilot_review_globs("mystery", config)
    expect_identical(globs$blog, "content/blog/**")
  })
})

describe("copilot_instruction_file", {
  it("prepends an applyTo frontmatter and the generated note", {
    out <- copilot_instruction_file(c("a/**", "b/**"), "  body text  ")
    expect_true(startsWith(out, "---\napplyTo: \"a/**,b/**\"\n---"))
    expect_true(grepl("Generated by jinx", out, fixed = TRUE))
    expect_true(grepl("body text", out, fixed = TRUE))
  })
})

describe("copilot_render_instructions", {
  skills <- list(
    brand = "BRAND CHECK",
    blog = "BLOG",
    social = "SOCIAL",
    translation = "TRANSLATION",
    brand_context = "BRAND RULESET"
  )
  globs <- list(
    brand = "**",
    blog = "content/blog/**",
    social = "social/**",
    translation = "i18n/**"
  )
  files <- copilot_render_instructions(skills, globs)

  it("produces the repo contract and four gate files", {
    expect_setequal(
      names(files),
      c(
        ".github/copilot-instructions.md",
        ".github/instructions/rladies-brand.instructions.md",
        ".github/instructions/rladies-blog.instructions.md",
        ".github/instructions/rladies-social.instructions.md",
        ".github/instructions/rladies-translation.instructions.md"
      )
    )
  })

  it("merges the brand ruleset and brand-check into the brand file", {
    brand <- files[[".github/instructions/rladies-brand.instructions.md"]]
    expect_true(grepl("BRAND RULESET", brand, fixed = TRUE))
    expect_true(grepl("BRAND CHECK", brand, fixed = TRUE))
    expect_true(grepl("applyTo: \"**\"", brand, fixed = TRUE))
  })

  it("scopes each surface gate to its globs", {
    blog <- files[[".github/instructions/rladies-blog.instructions.md"]]
    expect_true(grepl("applyTo: \"content/blog/**\"", blog, fixed = TRUE))
    expect_true(grepl("BLOG", blog, fixed = TRUE))
  })

  it("keeps the never-publish contract in the repo-wide file", {
    contract <- files[[".github/copilot-instructions.md"]]
    expect_true(grepl("Never approve, merge", contract, fixed = TRUE))
    expect_true(grepl("RLadies+", contract, fixed = TRUE))
  })
})

describe("copilot_fetch_skill", {
  it("decodes the SKILL.md and strips its frontmatter", {
    body <- "---\nname: run-blog-review\n---\n\n# Blog review\ncheck it"
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        list(content = jsonlite::base64_enc(charToRaw(body)))
      },
      .package = "gh"
    )
    config <- list(
      grimoire = list(owner = "rladies", repo = "grimoire", ref = "main")
    )
    out <- copilot_fetch_skill("run-blog-review", config)
    expect_true(startsWith(out, "# Blog review"))
  })
})

describe("copilot_put_file", {
  it("skips the PUT when content is unchanged", {
    calls <- character()
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        calls[[length(calls) + 1]] <<- endpoint
        if (startsWith(endpoint, "GET")) {
          return(list(
            content = jsonlite::base64_enc(charToRaw("same")),
            sha = "s"
          ))
        }
        list()
      },
      .package = "gh"
    )
    changed <- copilot_put_file("o", "r", "p", "same", "b", "m")
    expect_false(changed)
    expect_false(any(startsWith(calls, "PUT")))
  })

  it("PUTs with the existing sha when content differs", {
    calls <- character()
    local_mocked_bindings(
      gh = function(endpoint, ...) {
        calls[[length(calls) + 1]] <<- endpoint
        if (startsWith(endpoint, "GET")) {
          return(list(
            content = jsonlite::base64_enc(charToRaw("old")),
            sha = "s"
          ))
        }
        args <- list(...)
        expect_identical(args$sha, "s")
        list()
      },
      .package = "gh"
    )
    changed <- copilot_put_file("o", "r", "p", "new", "b", "m")
    expect_true(changed)
    expect_true(any(startsWith(calls, "PUT")))
  })
})

describe("copilot_sync_repo", {
  fake_skills <- list(
    brand = "b",
    blog = "bl",
    social = "s",
    translation = "t",
    brand_context = "ctx"
  )

  it("opens a PR when files changed", {
    local_mocked_bindings(
      copilot_gather_skills = function(config) fake_skills,
      gh_branch_upsert = function(...) "sha",
      copilot_put_file = function(...) TRUE,
      gh_open_or_update_pr = function(...) "https://github.com/rladies/x/pull/1"
    )
    result <- copilot_sync_repo("rladies", "x")
    expect_identical(result$status, "created")
    expect_identical(result$url, "https://github.com/rladies/x/pull/1")
  })

  it("reports unchanged and opens no PR when nothing changed", {
    opened <- FALSE
    local_mocked_bindings(
      copilot_gather_skills = function(config) fake_skills,
      gh_branch_upsert = function(...) "sha",
      copilot_put_file = function(...) FALSE,
      gh_open_or_update_pr = function(...) {
        opened <<- TRUE
        "url"
      }
    )
    result <- copilot_sync_repo("rladies", "x")
    expect_identical(result$status, "unchanged")
    expect_null(result$url)
    expect_false(opened)
  })
})
