mappings:
  - pattern: "^data/chapters/"
    label: "chapter"
  - pattern: "^data/directory/"
    label: "directory"
  - pattern: "^data/global_team/"
    label: "global-team"
  - pattern: "^data/rblogs/"
    label: "blog"
  - pattern: "^content/blog/"
    label: "blog"
  - pattern: "^content/about-us/"
    label: "about"
  - pattern: "\\.R$"
    label: "code"
  - pattern: "^\\.github/"
    label: "infrastructure"
  - pattern: "\\.json$"
    label: "data"
  - pattern: "^blogs/"
    label: "blog"
  - pattern: "^contact/"
    label: "directory"
