#' Compute activity trends
#'
#' Calculates month-over-month changes and rolling averages from
#' chapter activity data.
#'
#' @param activity_data Data frame from [collect_chapter_activity()].
#' @return Data frame with trend columns added.
#' @importFrom stats aggregate
#' @importFrom utils head
#' @export
compute_activity_trends <- function(activity_data) {
  if (nrow(activity_data) == 0) {
    return(data.frame(
      month = character(0),
      total_commits = integer(0),
      change = numeric(0),
      sparkline = character(0),
      stringsAsFactors = FALSE
    ))
  }

  monthly <- aggregate(
    commits ~ month,
    data = activity_data,
    FUN = sum
  )
  monthly <- monthly[order(monthly$month), ]

  monthly$change <- c(
    NA_real_,
    diff(monthly$commits) / head(monthly$commits, -1) * 100
  )
  monthly$sparkline <- compute_sparkline(monthly$commits)

  names(monthly)[names(monthly) == "commits"] <- "total_commits"
  monthly
}

#' Format analytics as markdown
#'
#' @param trends Data frame from [compute_activity_trends()].
#' @param contributor_growth Data frame from [collect_contributor_growth()].
#' @return Formatted markdown string.
#' @export
format_analytics_markdown <- function(trends, contributor_growth) {
  template_path <- system.file(
    "templates",
    "analytics-dashboard.md",
    package = "jinx"
  )

  if (nrow(trends) == 0 && nrow(contributor_growth) == 0) {
    return("## Analytics Dashboard\n\nNo data available.\n")
  }

  chapter_lines <- if (nrow(trends) > 0) {
    paste(
      "| Month | Commits | Change | Trend |",
      "|-------|---------|--------|-------|",
      paste(
        vapply(
          seq_len(nrow(trends)),
          function(i) {
            change_str <- if (is.na(trends$change[i])) {
              "-"
            } else {
              sprintf("%+.1f%%", trends$change[i])
            }
            cli::format_inline(paste0(
              "| {trends$month[i]} | {trends$total_commits[i]}",
              " | {change_str} | {trends$sparkline[i]} |"
            ))
          },
          character(1)
        ),
        collapse = "\n"
      ),
      sep = "\n"
    )
  } else {
    "No chapter activity data."
  }

  growth_lines <- if (nrow(contributor_growth) > 0) {
    paste(
      "| Month | New | Total |",
      "|-------|-----|-------|",
      paste(
        vapply(
          seq_len(nrow(contributor_growth)),
          function(i) {
            cli::format_inline(paste0(
              "| {contributor_growth$month[i]}",
              " | {contributor_growth$new_contributors[i]}",
              " | {contributor_growth$total_contributors[i]} |"
            ))
          },
          character(1)
        ),
        collapse = "\n"
      ),
      sep = "\n"
    )
  } else {
    "No contributor data."
  }

  if (nzchar(template_path)) {
    render_template(
      template_path,
      list(
        PERIOD = cli::format_inline(
          "{trends$month[1]} to {trends$month[nrow(trends)]}"
        ),
        CHAPTER_TRENDS = chapter_lines,
        CONTRIBUTOR_GROWTH = growth_lines,
        TOP_CHAPTERS = summarize_top_chapters(trends),
        TOP_CONTRIBUTORS = "",
        DATE = as.character(Sys.Date())
      )
    )
  } else {
    paste(
      "## Analytics Dashboard\n",
      "### Chapter Activity Trends\n",
      chapter_lines,
      "\n### Contributor Growth\n",
      growth_lines,
      cli::format_inline("\n_Generated by jinx on {Sys.Date()}_"),
      sep = "\n"
    )
  }
}

compute_sparkline <- function(values) {
  if (length(values) == 0) {
    return(character(0))
  }
  blocks <- c(
    "\u2581",
    "\u2582",
    "\u2583",
    "\u2584",
    "\u2585",
    "\u2586",
    "\u2587",
    "\u2588"
  )
  rng <- range(values, na.rm = TRUE)
  if (rng[1] == rng[2]) {
    return(rep(blocks[4], length(values)))
  }
  scaled <- (values - rng[1]) / (rng[2] - rng[1])
  indices <- pmin(floor(scaled * 7) + 1, 8)
  vapply(indices, function(i) blocks[i], character(1))
}

compute_growth_rate <- function(values) {
  if (length(values) < 2) {
    return(NA_real_)
  }
  (values[length(values)] - values[1]) / values[1] * 100
}

summarize_top_chapters <- function(trends) {
  if (nrow(trends) == 0) {
    return("No data.")
  }
  paste("Total commits:", sum(trends$total_commits))
}
