#' Generate conference coordination report
#'
#' Summarizes active CFPs, speaker recommendations, and upcoming deadlines.
#'
#' @param org GitHub organization.
#' @param repo Repository where CFP issues are tracked.
#' @return Formatted markdown string.
#' @export
generate_conference_report <- function(org = "rladies",
                                       repo = "global-team") {
  cli::cli_h2("Generating conference coordination report")

  cfps <- list_open_cfps(org = org, repo = repo)

  if (nrow(cfps) == 0) {
    cli::cli_alert_info("No active CFPs found")
    return("## Conference Coordination Report\n\nNo active CFPs.\n")
  }

  cfps$days_left <- as.integer(as.Date(cfps$deadline) - Sys.Date())
  cli::cli_alert_success("Found {nrow(cfps)} active CFP{?s}")

  lines <- vapply(seq_len(nrow(cfps)), function(i) {
    status <- if (!is.na(cfps$days_left[i]) && cfps$days_left[i] <= 7) {
      "URGENT"
    } else if (!is.na(cfps$days_left[i]) && cfps$days_left[i] <= 14) {
      "Soon"
    } else {
      "Open"
    }
    glue::glue(
      "| {cfps$conference[i]} | {cfps$deadline[i]} | {cfps$days_left[i]} days | {status} | [#{cfps$number[i]}]({cfps$url[i]}) |"
    )
  }, character(1))

  paste(
    "## Conference Coordination Report\n",
    glue::glue("**{nrow(cfps)} active CFPs**\n"),
    "| Conference | Deadline | Time Left | Status | Link |",
    "|------------|----------|-----------|--------|------|",
    paste(lines, collapse = "\n"),
    glue::glue("\n\n_Generated by jinx on {Sys.Date()}_"),
    sep = "\n"
  )
}
