#' Generate conference coordination report
#'
#' Summarizes active CFPs, speaker recommendations, and upcoming deadlines.
#'
#' @param org GitHub organization.
#' @param repo Repository where CFP issues are tracked.
#' @return Formatted markdown string.
#' @export
generate_conference_report <- function(org = "rladies", repo = "global-team") {
  cli::cli_h2("Generating conference coordination report")

  cfps <- list_open_cfps(org = org, repo = repo)

  if (nrow(cfps) == 0) {
    cli::cli_alert_info("No active CFPs found")
    return("## Conference Coordination Report\n\nNo active CFPs.\n")
  }

  cfps$days_left <- as.integer(as.Date(cfps$deadline) - Sys.Date())
  cfps$status <- ifelse(
    !is.na(cfps$days_left) & cfps$days_left <= 7,
    "URGENT",
    ifelse(
      !is.na(cfps$days_left) & cfps$days_left <= 14,
      "Soon",
      "Open"
    )
  )
  cli::cli_alert_success("Found {nrow(cfps)} active CFP{?s}")

  lines <- glue::glue_data(
    cfps,
    paste0(
      "| {conference} | {deadline} | {days_left} days",
      " | {status} | [#{number}]({url}) |"
    )
  )

  paste(
    "## Conference Coordination Report\n",
    cli::format_inline("**{nrow(cfps)} active CFPs**\n"),
    "| Conference | Deadline | Time Left | Status | Link |",
    "|------------|----------|-----------|--------|------|",
    paste(lines, collapse = "\n"),
    cli::format_inline("\n\n_Generated by jinx on {Sys.Date()}_"),
    sep = "\n"
  )
}
