#' Welcome a first-time contributor
#'
#' Checks if the PR/issue author has previous contributions to the repo.
#' If this is their first, posts a warm welcome message. If not first-time,
#' posts a shorter thank-you.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param number Issue or PR number.
#' @param author GitHub login of the author.
#' @param is_pr Whether this is a PR (TRUE) or issue (FALSE).
#' @param org Organization name.
#' @return Comment URL or `NULL` if author is a team member (invisibly).
#' @export
contributor_welcome <- function(
  owner,
  repo,
  number,
  author,
  is_pr = TRUE,
  org = "rladies"
) {
  if (is_bot(author)) {
    return(invisible(NULL))
  }

  if (is_team_member(author, org)) {
    return(invisible(NULL))
  }

  first_time <- is_first_time_contributor(owner, repo, author, is_pr)

  message <- if (first_time) {
    contributor_welcome_first_time(author, repo, is_pr)
  } else {
    contributor_welcome_returning(author, is_pr)
  }

  comment <- gh::gh(
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
    owner = owner,
    repo = repo,
    issue_number = number,
    body = message
  )

  cli::cli_alert_success("Welcomed {author} on {owner}/{repo}#{number}")
  invisible(comment$html_url)
}

#' Thank a contributor when their PR is merged
#'
#' Posts a thank-you message and adds the contributor to the repo's
#' contributor list if one exists.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param pr_number PR number.
#' @param author GitHub login of the PR author.
#' @param org Organization name.
#' @return Comment URL (invisibly).
#' @export
contributor_thank <- function(owner, repo, pr_number, author, org = "rladies") {
  if (is_bot(author)) {
    return(invisible(NULL))
  }

  first_time <- is_first_time_contributor(owner, repo, author, is_pr = TRUE)

  message <- if (first_time) {
    glue::glue(
      "Congratulations on your first contribution to **{repo}**, @{author}! ",
      "Thank you for helping make RLadies+ better.\n\n",
      "_Generated by jinx_"
    )
  } else {
    glue::glue(
      "Thank you for your contribution, @{author}!\n\n",
      "_Generated by jinx_"
    )
  }

  comment <- gh::gh(
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
    owner = owner,
    repo = repo,
    issue_number = pr_number,
    body = message
  )

  invisible(comment$html_url)
}

#' List contributors for a repository
#'
#' Collects all contributors from merged PRs and commits, returning
#' a deduplicated list with contribution counts.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param include_bots Whether to include bot accounts. Defaults to `FALSE`.
#' @return Data frame with `login`, `contributions`, `avatar_url`, and
#'   `profile_url` columns, sorted by contribution count.
#' @export
contributor_list <- function(owner, repo, include_bots = FALSE) {
  contributors <- tryCatch(
    gh::gh(
      "GET /repos/{owner}/{repo}/contributors",
      owner = owner,
      repo = repo,
      .limit = Inf
    ),
    error = function(e) list()
  )

  if (length(contributors) == 0) {
    cli::cli_alert_info("No contributors found for {owner}/{repo}")
    return(data.frame(
      login = character(0),
      contributions = integer(0),
      avatar_url = character(0),
      profile_url = character(0),
      stringsAsFactors = FALSE
    ))
  }

  df <- data.frame(
    login = vapply(contributors, function(c) c$login %||% "", character(1)),
    contributions = vapply(
      contributors,
      function(c) c$contributions %||% 0L,
      integer(1)
    ),
    avatar_url = vapply(
      contributors,
      function(c) c$avatar_url %||% "",
      character(1)
    ),
    profile_url = vapply(
      contributors,
      function(c) c$html_url %||% "",
      character(1)
    ),
    type = vapply(contributors, function(c) c$type %||% "User", character(1)),
    stringsAsFactors = FALSE
  )

  if (!include_bots) {
    df <- df[df$type == "User", ]
  }
  df$type <- NULL
  df <- df[order(-df$contributions), ]
  row.names(df) <- NULL

  cli::cli_alert_info(
    "Found {nrow(df)} contributors to {owner}/{repo}"
  )
  df
}

#' Generate a contributors markdown section
#'
#' Creates a markdown table or image grid of contributors for
#' inclusion in README or other documents.
#'
#' @param contributors Data frame from [contributor_list()].
#' @param format Output format: `"table"` or `"grid"`.
#' @param cols Number of columns for grid format. Defaults to 7.
#' @return Character string with markdown content.
#' @export
contributor_format <- function(
  contributors,
  format = c("table", "grid"),
  cols = 7
) {
  format <- match.arg(format)

  if (nrow(contributors) == 0) {
    return("No contributors yet.")
  }

  if (format == "table") {
    contributor_format_table(contributors)
  } else {
    contributor_format_grid(contributors, cols)
  }
}

#' Generate and update a contributors list for a repo
#'
#' Fetches contributors and creates/updates a PR with the contributor
#' list in a specified file.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param file_path Path in the repo to update with the contributor list.
#'   Defaults to `".github/contributors.md"`.
#' @param format Format for the contributor list.
#' @return PR URL if changes were made, `NULL` otherwise (invisibly).
#' @export
contributor_update <- function(
  owner,
  repo,
  file_path = ".github/contributors.md",
  format = "grid"
) {
  contributors <- contributor_list(owner, repo)
  if (nrow(contributors) == 0) {
    return(invisible(NULL))
  }

  content <- paste0(
    "# Contributors\n\n",
    "Thanks to all our contributors!\n\n",
    contributor_format(contributors, format = format),
    "\n\n_Last updated: ",
    Sys.Date(),
    "_\n",
    "\n_Generated by jinx_\n"
  )

  existing <- tryCatch(
    gh::gh(
      "GET /repos/{owner}/{repo}/contents/{path}",
      owner = owner,
      repo = repo,
      path = file_path
    ),
    error = function(e) NULL
  )

  if (!is.null(existing)) {
    existing_content <- rawToChar(jsonlite::base64_dec(existing$content))
    if (trimws(existing_content) == trimws(content)) {
      cli::cli_alert_info("Contributors list is up to date")
      return(invisible(NULL))
    }
  }

  branch <- "jinx/update-contributors"
  main_ref <- gh::gh(
    "GET /repos/{owner}/{repo}/git/ref/heads/main",
    owner = owner,
    repo = repo
  )

  tryCatch(
    gh::gh(
      "POST /repos/{owner}/{repo}/git/refs",
      owner = owner,
      repo = repo,
      ref = glue::glue("refs/heads/{branch}"),
      sha = main_ref$object$sha
    ),
    error = function(e) {
      gh::gh(
        "PATCH /repos/{owner}/{repo}/git/refs/heads/{branch}",
        owner = owner,
        repo = repo,
        branch = branch,
        sha = main_ref$object$sha,
        force = TRUE
      )
    }
  )

  content_b64 <- jsonlite::base64_enc(charToRaw(content))
  params <- list(
    owner = owner,
    repo = repo,
    path = file_path,
    message = "Update contributors list",
    content = content_b64,
    branch = branch
  )
  if (!is.null(existing)) {
    params$sha <- existing$sha
  }
  do.call(gh::gh, c("PUT /repos/{owner}/{repo}/contents/{path}", params))

  pr <- gh::gh(
    "POST /repos/{owner}/{repo}/pulls",
    owner = owner,
    repo = repo,
    title = "Update contributors list",
    head = branch,
    base = "main",
    body = paste0(
      "Automated update of the contributors list.\n\n",
      "- **Total contributors**: ",
      nrow(contributors),
      "\n\n",
      "_Created by jinx_"
    )
  )

  cli::cli_alert_success("Contributors PR created: {pr$html_url}")
  invisible(pr$html_url)
}

#' Collect contributors across multiple repos
#'
#' Aggregates contributor data across all non-meetup repos in the org.
#'
#' @param org GitHub organization.
#' @param exclude_pattern Regex to exclude repos.
#' @return Data frame with `login`, `repos`, `contributions`,
#'   `avatar_url`, and `profile_url`. `contributions` is the sum across
#'   all repos; `repos` is the count of distinct repos contributed to.
#' @export
contributor_list_org <- function(
  org = "rladies",
  exclude_pattern = "^meetup-"
) {
  repos <- gh::gh(
    "GET /orgs/{org}/repos",
    org = org,
    type = "all",
    .limit = Inf
  )
  repos <- Filter(function(r) !grepl(exclude_pattern, r$name), repos)

  cli::cli_alert_info("Scanning {length(repos)} repos for contributors")

  all_contribs <- list()
  for (r in repos) {
    contribs <- tryCatch(
      gh::gh(
        "GET /repos/{owner}/{repo}/contributors",
        owner = org,
        repo = r$name,
        .limit = Inf
      ),
      error = function(e) list()
    )

    for (c in contribs) {
      if (is.null(c$login) || c$type != "User") {
        next
      }
      login <- c$login
      if (is.null(all_contribs[[login]])) {
        all_contribs[[login]] <- list(
          login = login,
          repos = list(),
          total = 0L,
          avatar_url = c$avatar_url %||% "",
          profile_url = c$html_url %||% ""
        )
      }
      all_contribs[[login]]$repos <- c(
        all_contribs[[login]]$repos,
        r$name
      )
      all_contribs[[login]]$total <- all_contribs[[login]]$total +
        (c$contributions %||% 0L)
    }
  }

  if (length(all_contribs) == 0) {
    return(data.frame(
      login = character(0),
      repos = integer(0),
      contributions = integer(0),
      avatar_url = character(0),
      profile_url = character(0),
      stringsAsFactors = FALSE
    ))
  }

  df <- data.frame(
    login = vapply(all_contribs, function(x) x$login, character(1)),
    repos = vapply(
      all_contribs,
      function(x) length(unique(x$repos)),
      integer(1)
    ),
    contributions = vapply(all_contribs, function(x) x$total, integer(1)),
    avatar_url = vapply(all_contribs, function(x) x$avatar_url, character(1)),
    profile_url = vapply(all_contribs, function(x) x$profile_url, character(1)),
    stringsAsFactors = FALSE
  )

  df <- df[order(-df$contributions), ]
  row.names(df) <- NULL
  cli::cli_alert_success(
    "Found {nrow(df)} unique contributors across {length(repos)} repos"
  )
  df
}

is_first_time_contributor <- function(owner, repo, author, is_pr = TRUE) {
  if (is_pr) {
    prs <- tryCatch(
      gh::gh(
        "GET /repos/{owner}/{repo}/pulls",
        owner = owner,
        repo = repo,
        state = "all",
        .limit = 10,
        creator = author
      ),
      error = function(e) list()
    )
    length(prs) <= 1
  } else {
    issues <- tryCatch(
      gh::gh(
        "GET /repos/{owner}/{repo}/issues",
        owner = owner,
        repo = repo,
        state = "all",
        .limit = 10,
        creator = author
      ),
      error = function(e) list()
    )
    real_issues <- Filter(function(i) is.null(i$pull_request), issues)
    length(real_issues) <= 1
  }
}

is_team_member <- function(author, org) {
  tryCatch(
    {
      gh::gh(
        "GET /orgs/{org}/teams/global/memberships/{username}",
        org = org,
        username = author
      )
      TRUE
    },
    error = function(e) FALSE
  )
}

is_bot <- function(login) {
  grepl("\\[bot\\]$", login) || login %in% c("github-actions", "dependabot")
}

contributor_welcome_first_time <- function(author, repo, is_pr) {
  type <- if (is_pr) "pull request" else "issue"
  glue::glue(
    "Welcome to **{repo}**, @{author}! ",
    "This is your first {type} here - thank you for contributing!\n\n",
    "We are a volunteer organisation, so it may take us a little while ",
    "to review, but we will get back to you as soon as we can.\n\n",
    "_Generated by jinx_"
  )
}

contributor_welcome_returning <- function(author, is_pr) {
  type <- if (is_pr) "pull request" else "issue"
  glue::glue(
    "Thanks for the {type}, @{author}! ",
    "We will get back to you as soon as we can.\n\n",
    "_Generated by jinx_"
  )
}

contributor_format_table <- function(contributors) {
  header <- paste0(
    "| Avatar | Contributor | Contributions |\n",
    "|--------|-------------|---------------|\n"
  )
  rows <- vapply(
    seq_len(nrow(contributors)),
    function(i) {
      c <- contributors[i, ]
      glue::glue(
        "| <img src=\"{c$avatar_url}\" width=\"30\"> | ",
        "[@{c$login}]({c$profile_url}) | {c$contributions} |"
      )
    },
    character(1)
  )
  paste0(header, paste(rows, collapse = "\n"), "\n")
}

contributor_format_grid <- function(contributors, cols) {
  rows <- ceiling(nrow(contributors) / cols)
  cells <- vapply(
    seq_len(nrow(contributors)),
    function(i) {
      c <- contributors[i, ]
      glue::glue(
        "<a href=\"{c$profile_url}\">",
        "<img src=\"{c$avatar_url}\" width=\"60\" title=\"@{c$login}\">",
        "</a>"
      )
    },
    character(1)
  )

  grid_rows <- vapply(
    seq_len(rows),
    function(r) {
      start <- (r - 1) * cols + 1
      end <- min(r * cols, length(cells))
      paste(cells[start:end], collapse = " ")
    },
    character(1)
  )

  paste(grid_rows, collapse = "\n\n")
}
