#' Load the Copilot review bridge configuration
#'
#' Locates the grimoire source skills and the per-repository file globs
#' each review gate watches. See `inst/config/copilot-review.yml`.
#'
#' @return Named list with `grimoire` and `repos` entries.
#' @export
load_copilot_review_config <- function() {
  path <- system.file("config", "copilot-review.yml", package = "jinx")
  if (!nzchar(path)) {
    cli::cli_abort("copilot-review.yml not found in jinx package")
  }
  yaml::read_yaml(path)
}

#' Resolve the gate-to-globs map for a target repository
#'
#' @param repo Target repository name.
#' @param config Config from [load_copilot_review_config()].
#' @return Named list mapping each gate to a character vector of globs.
#' @keywords internal
#' @noRd
copilot_review_globs <- function(repo, config = load_copilot_review_config()) {
  config$repos[[repo]] %||% config$repos$default
}

#' Strip a leading YAML frontmatter block from skill text
#'
#' Grimoire skills carry their own `--- name/description ---` frontmatter;
#' Copilot instruction files need their own `applyTo` frontmatter instead,
#' so the skill's block is removed before embedding its body.
#'
#' @param text Raw `SKILL.md` contents.
#' @return The body with any leading frontmatter block removed.
#' @keywords internal
#' @noRd
copilot_strip_frontmatter <- function(text) {
  if (!grepl("^---[ \t]*\n", text, perl = TRUE)) {
    return(text)
  }
  body <- sub(
    "^---[ \t]*\n(?:.|\n)*?\n---[ \t]*(?:\n|$)",
    "",
    text,
    perl = TRUE
  )
  sub("^\n+", "", body)
}

#' Fetch one grimoire skill body
#'
#' @param skill Skill directory name under `skills/`.
#' @param config Config from [load_copilot_review_config()].
#' @return The skill body (frontmatter stripped) as a string.
#' @keywords internal
#' @noRd
copilot_fetch_skill <- function(skill, config = load_copilot_review_config()) {
  g <- config$grimoire
  path <- glue::glue("skills/{skill}/SKILL.md")
  resp <- gh::gh(
    "GET /repos/{owner}/{repo}/contents/{path}",
    owner = g$owner,
    repo = g$repo,
    path = path,
    ref = g$ref
  )
  copilot_strip_frontmatter(base64_decode(resp$content))
}

#' Fetch the review-gate skills plus the shared brand ruleset
#'
#' @param config Config from [load_copilot_review_config()].
#' @return Named list of skill bodies keyed by gate, plus `brand_context`.
#' @keywords internal
#' @noRd
copilot_gather_skills <- function(config = load_copilot_review_config()) {
  gates <- config$grimoire$gates
  skills <- lapply(gates, copilot_fetch_skill, config = config)
  skills$brand_context <- copilot_fetch_skill(
    config$grimoire$brand_context,
    config = config
  )
  skills
}

#' Compose one Copilot path-scoped instruction file
#'
#' @param apply_to Character vector of globs for the `applyTo` frontmatter.
#' @param body Instruction body.
#' @return The full file contents as a string.
#' @keywords internal
#' @noRd
copilot_instruction_file <- function(apply_to, body) {
  paste0(
    "---\n",
    "applyTo: \"",
    paste(apply_to, collapse = ","),
    "\"\n",
    "---\n\n",
    copilot_generated_note(),
    "\n\n",
    trimws(body),
    "\n"
  )
}

#' Repo-wide review contract written to `.github/copilot-instructions.md`
#'
#' @keywords internal
#' @noRd
copilot_repo_contract <- function() {
  paste0(
    "# RLadies+ review gate\n\n",
    copilot_generated_note(),
    "\n\n",
    "You are acting as the RLadies+ pre-human review gate for this ",
    "repository. When reviewing a pull request, apply the RLadies+ brand ",
    "and voice rules together with the surface-specific checklists in ",
    "`.github/instructions/`.\n\n",
    "Report findings as a tiered punch list, most severe first:\n\n",
    "- \u26d4 **Blockers** \u2014 must be fixed before human review.\n",
    "- \u26a0\ufe0f **Warnings** \u2014 should be fixed first.\n",
    "- \U0001f49c **Nits** \u2014 optional polish.\n\n",
    "For each finding give the location and a concrete suggested fix. ",
    "Never approve, merge, schedule, or publish \u2014 hand a punch list to ",
    "the human reviewers. Always write \"RLadies+\" (never \"R-Ladies\", ",
    "\"R-Ladies+\", or \"RLadies\").\n"
  )
}

#' @keywords internal
#' @noRd
copilot_generated_note <- function() {
  paste0(
    "<!-- Generated by jinx from rladies/grimoire. Do not edit by hand; ",
    "run `/jinx copilot-sync` to refresh. -->"
  )
}

#' Render the full set of Copilot instruction files
#'
#' The brand gate is always-on (`applyTo` defaults to every file) and
#' carries both the foundation ruleset and the brand-check checklist, so
#' it is loaded alongside any surface-specific gate a PR triggers.
#'
#' @param skills Skill bodies from `copilot_gather_skills()`.
#' @param globs Gate-to-globs map from `copilot_review_globs()`.
#' @return Named list mapping repo file paths to file contents.
#' @keywords internal
#' @noRd
copilot_render_instructions <- function(skills, globs) {
  brand_body <- paste(
    skills$brand_context,
    skills$brand,
    sep = "\n\n---\n\n"
  )
  gate_body <- list(
    brand = brand_body,
    blog = skills$blog,
    social = skills$social,
    translation = skills$translation
  )

  files <- list(".github/copilot-instructions.md" = copilot_repo_contract())
  for (gate in names(gate_body)) {
    path <- as.character(glue::glue(
      ".github/instructions/rladies-{gate}.instructions.md"
    ))
    files[[path]] <- copilot_instruction_file(
      globs[[gate]] %||% "**",
      gate_body[[gate]]
    )
  }
  files
}

#' Create or update one file on a branch, skipping no-op writes
#'
#' @return `TRUE` if a commit was pushed, `FALSE` if content was unchanged.
#' @keywords internal
#' @noRd
copilot_put_file <- function(owner, repo, path, content, branch, message) {
  existing <- tryCatch(
    gh::gh(
      "GET /repos/{owner}/{repo}/contents/{path}",
      owner = owner,
      repo = repo,
      path = path,
      ref = branch
    ),
    error = function(e) NULL
  )
  if (
    !is.null(existing) && identical(base64_decode(existing$content), content)
  ) {
    return(FALSE)
  }

  params <- list(
    owner = owner,
    repo = repo,
    path = path,
    message = message,
    content = jsonlite::base64_enc(charToRaw(content)),
    branch = branch
  )
  if (!is.null(existing)) {
    params$sha <- existing$sha
  }
  do.call(gh::gh, c("PUT /repos/{owner}/{repo}/contents/{path}", params))
  TRUE
}

#' Sync grimoire review skills into a repo as Copilot instructions
#'
#' Fetches the four grimoire review-gate skills (plus the foundation brand
#' ruleset) and lands them in `owner/repo` as
#' `.github/copilot-instructions.md` and path-scoped
#' `.github/instructions/*.instructions.md` files, via a pull request.
#' This is what makes GitHub Copilot's code review grimoire-aware. Re-run
#' whenever grimoire changes to refresh the instructions.
#'
#' @param owner Target repository owner. Defaults to `"rladies"`.
#' @param repo Target repository name.
#' @param base Base branch. Defaults to `"main"`.
#' @param branch Working branch. Defaults to
#'   `"jinx/copilot-review-instructions"`.
#' @param config Config from [load_copilot_review_config()].
#' @return A list with `status` (`"created"` or `"unchanged"`) and `url`
#'   (the PR URL when created).
#' @export
copilot_sync_repo <- function(
  owner = "rladies",
  repo,
  base = "main",
  branch = "jinx/copilot-review-instructions",
  config = load_copilot_review_config()
) {
  skills <- copilot_gather_skills(config)
  globs <- copilot_review_globs(repo, config)
  files <- copilot_render_instructions(skills, globs)

  gh_branch_upsert(owner, repo, branch, base = base)
  message <- "Sync RLadies+ Copilot review instructions from grimoire"
  written <- vapply(
    names(files),
    function(path) {
      copilot_put_file(owner, repo, path, files[[path]], branch, message)
    },
    logical(1)
  )

  if (!any(written)) {
    cli::cli_alert_info("Copilot review instructions already up to date")
    return(list(status = "unchanged", url = NULL))
  }

  url <- gh_open_or_update_pr(
    owner,
    repo,
    branch,
    base = base,
    title = "Sync RLadies+ Copilot review instructions",
    body = paste0(
      "Syncs the RLadies+ Copilot review gates from ",
      "[rladies/grimoire](https://github.com/rladies/grimoire) so Copilot ",
      "code review applies the brand, blog, social, and translation ",
      "checklists.\n\n_Generated by jinx_"
    )
  )
  cli::cli_alert_success("Copilot review instructions PR: {url}")
  list(status = "created", url = url)
}
