#' The GitHub login used to request Copilot as a PR reviewer
#'
#' Isolated so the exact reviewer slug can be swapped in one place if
#' GitHub changes it (currently `copilot-pull-request-reviewer[bot]`).
#'
#' @keywords internal
#' @noRd
copilot_reviewer_login <- function() {
  "copilot-pull-request-reviewer[bot]"
}

#' The owner/repo the current command is running in
#'
#' Reads `GITHUB_REPOSITORY` (set by GitHub Actions), falling back to
#' `rladies/jinx`. Used as the default target when a PR reference omits
#' the repository.
#'
#' @return A list with `owner` and `repo`.
#' @keywords internal
#' @noRd
command_default_repo <- function() {
  slug <- Sys.getenv("GITHUB_REPOSITORY", "rladies/jinx")
  parts <- strsplit(slug, "/", fixed = TRUE)[[1]]
  if (length(parts) != 2) {
    return(list(owner = "rladies", repo = "jinx"))
  }
  list(owner = parts[1], repo = parts[2])
}

#' Parse a pull request reference
#'
#' Accepts `#42`, `42`, `owner/repo#42`, or a full PR URL. When only a
#' number is given, the owner and repo default to the current command's
#' repository.
#'
#' @param ref The reference string.
#' @param default_owner Owner to use for bare-number references.
#' @param default_repo Repo to use for bare-number references.
#' @return A list with `owner`, `repo`, and `number`, or `NULL` if the
#'   reference cannot be parsed.
#' @keywords internal
#' @noRd
parse_pr_ref <- function(
  ref,
  default_owner = command_default_repo()$owner,
  default_repo = command_default_repo()$repo
) {
  ref <- trimws(ref %||% "")

  url <- regmatches(
    ref,
    regexec("github\\.com/([^/]+)/([^/]+)/pull/([0-9]+)", ref)
  )[[1]]
  if (length(url) == 4) {
    return(list(owner = url[2], repo = url[3], number = as.integer(url[4])))
  }

  slug <- regmatches(
    ref,
    regexec("^([^/[:space:]]+)/([^#[:space:]]+)#([0-9]+)$", ref)
  )[[1]]
  if (length(slug) == 4) {
    return(list(owner = slug[2], repo = slug[3], number = as.integer(slug[4])))
  }

  num <- regmatches(ref, regexec("^#?([0-9]+)$", ref))[[1]]
  if (length(num) == 2) {
    return(list(
      owner = default_owner,
      repo = default_repo,
      number = as.integer(num[2])
    ))
  }

  NULL
}

#' Human-readable label for a review gate
#'
#' @param gate Gate key (`brand`, `blog`, `social`, `translation`), or
#'   `NULL` for a full review.
#' @param config Config from [load_copilot_review_config()].
#' @keywords internal
#' @noRd
copilot_gate_label <- function(gate, config = load_copilot_review_config()) {
  if (is.null(gate)) {
    return("brand & voice + surface")
  }
  skill <- config$grimoire$gates[[gate]]
  if (is.null(skill)) {
    return(gate)
  }
  glue::glue("{gate} ({skill})")
}

#' Comment posted on the PR when Copilot is summoned
#'
#' @keywords internal
#' @noRd
copilot_scope_comment <- function(gate_label) {
  paste0(
    "\U0001fa84 jinx has summoned **GitHub Copilot** to run the RLadies+ ",
    "**",
    gate_label,
    "** review gate on this pull request.\n\n",
    "Copilot will post its findings as \u26d4 Blockers / ",
    "\u26a0\ufe0f Warnings / \U0001f49c Nits. This is a pre-human review ",
    "gate: it does not approve, ",
    "merge, schedule, or publish.\n\n_Generated by jinx_"
  )
}

#' Request GitHub Copilot as a reviewer on a pull request
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param pr_number Pull request number.
#' @param reviewer Copilot reviewer login.
#' @return `TRUE` if the request was accepted, `FALSE` otherwise.
#' @export
copilot_request_review <- function(
  owner,
  repo,
  pr_number,
  reviewer = copilot_reviewer_login()
) {
  tryCatch(
    {
      gh::gh(
        "POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers",
        owner = owner,
        repo = repo,
        pull_number = pr_number,
        reviewers = list(reviewer)
      )
      cli::cli_alert_success(
        "Requested Copilot review on {owner}/{repo}#{pr_number}"
      )
      TRUE
    },
    error = function(e) {
      cli::cli_alert_warning(
        "Copilot review request failed: {conditionMessage(e)}"
      )
      FALSE
    }
  )
}

#' Summon a GitHub Copilot review on a pull request
#'
#' Requests Copilot as a reviewer and posts a short scoping comment naming
#' the grimoire gate. Copilot then applies the instruction files synced by
#' [copilot_sync_repo()]. Returns a status message suitable for replying to
#' the requester.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param pr_number Pull request number.
#' @param gate Gate key (`brand`, `blog`, `social`, `translation`), or
#'   `NULL` for a full review.
#' @param comment Whether to post the scoping comment. Defaults to `TRUE`.
#' @param config Config from [load_copilot_review_config()].
#' @return A status string.
#' @export
copilot_review_pr <- function(
  owner,
  repo,
  pr_number,
  gate = NULL,
  comment = TRUE,
  config = load_copilot_review_config()
) {
  requested <- copilot_request_review(owner, repo, pr_number)
  gate_label <- copilot_gate_label(gate, config = config)

  if (comment && requested) {
    gh::gh(
      "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
      owner = owner,
      repo = repo,
      issue_number = pr_number,
      body = copilot_scope_comment(gate_label)
    )
  }

  target <- glue::glue("{owner}/{repo}#{pr_number}")
  if (requested) {
    glue::glue(
      "\U0001fa84 Summoned Copilot's {gate_label} review on {target} \u2014 ",
      "findings will post there shortly."
    )
  } else {
    glue::glue(
      "\U0001f63f I asked Copilot to review {target} but the request ",
      "didn't go through. It may already be reviewing, or Copilot code ",
      "review may not be enabled on that repo."
    )
  }
}
