#' List events for a chapter
#'
#' Queries Meetup Pro for recent events.
#'
#' @param chapter Chapter identifier (e.g. "rladies-berlin").
#' @param months Number of months of history.
#' @return Data frame with columns: title, date, url, rsvp_count, source,
#'   chapter.
#' @export
list_chapter_events <- function(chapter, months = 3) {
  events <- tryCatch({
    meetup_list_events(chapter, months = months)
  }, error = function(e) {
    cli::cli_alert_warning("Meetup fetch failed for {chapter}: {e$message}")
    empty_event_df()
  })

  if (nrow(events) == 0) {
    return(empty_event_df())
  }

  events[order(events$date, decreasing = TRUE), ]
}

#' Sync events across all chapters
#'
#' Fetches events from all configured sources and writes a summary.
#'
#' @param org GitHub organization.
#' @param target_repo Repository for the event archive.
#' @param months Number of months of history.
#' @param dry_run If `TRUE`, print what would be synced without acting.
#' @return Data frame of all events (invisibly).
#' @export
sync_chapter_events <- function(org = "rladies",
                                target_repo = "event-archive",
                                months = 3,
                                dry_run = TRUE) {
  cli::cli_h2("Syncing chapter events for {org}")

  config <- load_events_config()
  chapters <- config$chapters %||% character(0)

  if (length(chapters) == 0) {
    cli::cli_alert_warning("No chapters configured in events.yml")
    return(invisible(empty_event_df()))
  }

  all_events <- list()

  for (ch in chapters) {
    cli::cli_alert_info("Fetching events for {ch}")
    events <- list_chapter_events(ch, months = months)
    if (nrow(events) > 0) {
      all_events[[length(all_events) + 1]] <- events
    }
  }

  if (length(all_events) == 0) {
    cli::cli_alert_info("No events found")
    return(invisible(empty_event_df()))
  }

  combined <- do.call(rbind, all_events)
  cli::cli_alert_success("Found {nrow(combined)} events across {length(chapters)} chapters")

  if (dry_run) {
    cli::cli_alert_info("Dry run: skipping write")
    return(invisible(combined))
  }

  json <- jsonlite::toJSON(
    combined,
    pretty = TRUE,
    auto_unbox = TRUE,
    dataframe = "rows"
  )
  path <- file.path(tempdir(), "events.json")
  writeLines(json, path)

  cli::cli_alert_success("Event data written to {path}")
  invisible(combined)
}

#' Create a formatted event summary
#'
#' @param events Data frame from [list_chapter_events()] or
#'   [sync_chapter_events()].
#' @param period Summary period label.
#' @return Formatted markdown string.
#' @export
create_event_summary <- function(events, period = c("weekly", "monthly")) {
  period <- match.arg(period)

  if (nrow(events) == 0) {
    return(cli::format_inline(
      "## Event Summary - {period}\n\nNo events found for this period.\n\n_Generated by jinx on {Sys.Date()}_"
    ))
  }

  template_path <- system.file("templates", "event-summary.md", package = "jinx")
  if (!nzchar(template_path)) {
    return(format_event_summary_inline(events, period))
  }

  event_lines <- vapply(seq_len(nrow(events)), function(i) {
    e <- events[i, ]
    cli::format_inline("| {e$chapter} | [{e$title}]({e$url}) | {e$date} | {e$rsvp_count} | {e$source} |")
  }, character(1))

  event_list <- paste(
    "| Chapter | Event | Date | RSVPs | Source |",
    "|---------|-------|------|-------|--------|",
    paste(event_lines, collapse = "\n"),
    sep = "\n"
  )

  render_template(template_path, list(
    PERIOD = period,
    EVENT_COUNT = as.character(nrow(events)),
    CHAPTER_COUNT = as.character(length(unique(events$chapter))),
    EVENT_LIST = event_list,
    DATE = as.character(Sys.Date())
  ))
}

#' Publish event summary as a GitHub issue
#'
#' @param summary Formatted summary from [create_event_summary()].
#' @param org GitHub organization.
#' @param target_repo Repository to publish to.
#' @return Issue URL (invisibly).
#' @export
publish_event_summary <- function(summary,
                                  org = "rladies",
                                  target_repo = "global-team") {
  issue <- gh::gh(
    "POST /repos/{owner}/{repo}/issues",
    owner = org, repo = target_repo,
    title = cli::format_inline("Event Summary - {Sys.Date()}"),
    body = summary,
    labels = list("report", "events")
  )

  cli::cli_alert_success("Event summary published: {issue$html_url}")
  invisible(issue$html_url)
}

#' Load events configuration
#'
#' @return Named list from `inst/config/events.yml`.
#' @keywords internal
load_events_config <- function() {
  path <- system.file("config", "events.yml", package = "jinx")
  if (!nzchar(path)) {
    cli::cli_abort("events.yml not found in jinx package")
  }
  yaml::read_yaml(path)
}

#' Create an empty events data frame
#'
#' @return Data frame with 0 rows and standard event columns.
#' @keywords internal
empty_event_df <- function() {
  data.frame(
    title = character(0),
    date = as.Date(character(0)),
    url = character(0),
    rsvp_count = integer(0),
    source = character(0),
    chapter = character(0),
    stringsAsFactors = FALSE
  )
}

format_event_summary_inline <- function(events, period) {
  event_lines <- vapply(seq_len(nrow(events)), function(i) {
    e <- events[i, ]
    cli::format_inline("- **{e$chapter}**: [{e$title}]({e$url}) ({e$date}, {e$rsvp_count} RSVPs)")
  }, character(1))

  cli::format_inline(
    "## Event Summary - {period}\n\n**{nrow(events)} events** across **{length(unique(events$chapter))} chapters**\n\n{paste(event_lines, collapse = '\n')}\n\n_Generated by jinx on {Sys.Date()}_"
  )
}
