#' Welcome a contributor on a new PR or issue
#'
#' Checks if the PR/issue author has previous contributions to the repo.
#' If this is their first, posts a warm welcome message. If not, posts a
#' shorter thank-you. No-op for bots and global team members.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param number Issue or PR number.
#' @param author GitHub login of the author.
#' @param is_pr Whether this is a PR (TRUE) or issue (FALSE).
#' @param org Organization name.
#' @return Comment URL or `NULL` if author is a team member (invisibly).
#' @export
gh_welcome_contributor <- function(
  owner,
  repo,
  number,
  author,
  is_pr = TRUE,
  org = "rladies"
) {
  if (is_bot(author)) {
    return(invisible(NULL))
  }

  if (is_team_member(author, org)) {
    return(invisible(NULL))
  }

  first_time <- is_first_time_contributor(owner, repo, author, is_pr)

  message <- if (first_time) {
    gh_welcome_message_first_time(author, repo, is_pr)
  } else {
    gh_welcome_message_returning(author, is_pr)
  }

  comment <- gh::gh(
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
    owner = owner,
    repo = repo,
    issue_number = number,
    body = message
  )

  cli::cli_alert_success("Welcomed {author} on {owner}/{repo}#{number}")
  invisible(comment$html_url)
}

#' Thank a contributor when their PR is merged
#'
#' Posts a thank-you message tailored to whether this is their first
#' merged PR.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param pr_number PR number.
#' @param author GitHub login of the PR author.
#' @param org Organization name.
#' @return Comment URL (invisibly).
#' @export
gh_thank_contributor <- function(
  owner,
  repo,
  pr_number,
  author,
  org = "rladies"
) {
  if (is_bot(author)) {
    return(invisible(NULL))
  }

  first_time <- is_first_time_contributor(owner, repo, author, is_pr = TRUE)

  message <- if (first_time) {
    glue::glue(
      "Congratulations on your first contribution to **{repo}**, @{author}! ",
      "Thank you for helping make RLadies+ better.\n\n",
      "_Generated by jinx_"
    )
  } else {
    glue::glue(
      "Thank you for your contribution, @{author}!\n\n",
      "_Generated by jinx_"
    )
  }

  comment <- gh::gh(
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
    owner = owner,
    repo = repo,
    issue_number = pr_number,
    body = message
  )

  invisible(comment$html_url)
}

#' Greet a new PR author
#'
#' Thin wrapper around [gh_welcome_contributor()] that fixes `is_pr =
#' TRUE` for use in PR-only workflows. Reusable across any repo.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param number PR number.
#' @param author GitHub login of the author.
#' @param org Organization name.
#' @return Comment URL or `NULL` if author is a team member (invisibly).
#' @export
gh_greet_contributor <- function(owner, repo, number, author, org = "rladies") {
  gh_welcome_contributor(owner, repo, number, author, is_pr = TRUE, org = org)
}

is_first_time_contributor <- function(owner, repo, author, is_pr = TRUE) {
  if (is_pr) {
    prs <- tryCatch(
      gh::gh(
        "GET /repos/{owner}/{repo}/pulls",
        owner = owner,
        repo = repo,
        state = "all",
        .limit = 10,
        creator = author
      ),
      error = function(e) list()
    )
    length(prs) <= 1
  } else {
    issues <- tryCatch(
      gh::gh(
        "GET /repos/{owner}/{repo}/issues",
        owner = owner,
        repo = repo,
        state = "all",
        .limit = 10,
        creator = author
      ),
      error = function(e) list()
    )
    real_issues <- Filter(function(i) is.null(i$pull_request), issues)
    length(real_issues) <= 1
  }
}

is_team_member <- function(author, org) {
  tryCatch(
    {
      gh::gh(
        "GET /orgs/{org}/teams/global/memberships/{username}",
        org = org,
        username = author
      )
      TRUE
    },
    error = function(e) FALSE
  )
}

is_bot <- function(login) {
  grepl("\\[bot\\]$", login) || login %in% c("github-actions", "dependabot")
}

gh_welcome_message_first_time <- function(author, repo, is_pr) {
  type <- if (is_pr) "pull request" else "issue"
  glue::glue(
    "Welcome to **{repo}**, @{author}! ",
    "This is your first {type} here - thank you for contributing!\n\n",
    "We are a volunteer organisation, so it may take us a little while ",
    "to review, but we will get back to you as soon as we can.\n\n",
    "_Generated by jinx_"
  )
}

gh_welcome_message_returning <- function(author, is_pr) {
  type <- if (is_pr) "pull request" else "issue"
  glue::glue(
    "Thanks for the {type}, @{author}! ",
    "We will get back to you as soon as we can.\n\n",
    "_Generated by jinx_"
  )
}
