#' Post a review checklist comment on a PR
#'
#' Generates a context-aware checklist based on the types of files changed.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param pr_number PR number.
#' @param file_paths Character vector of changed file paths.
#' @return Posted comment URL (invisibly).
#' @keywords internal
#' @noRd
post_checklist <- function(owner, repo, pr_number, file_paths) {
  checklist <- build_checklist(file_paths, repo)
  if (is.null(checklist)) return(invisible(NULL))

  comment <- gh::gh(
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
    owner = owner, repo = repo, issue_number = pr_number,
    body = checklist
  )

  invisible(comment$html_url)
}

build_checklist <- function(file_paths, repo) {
  sections <- character(0)

  has_json <- any(grepl("\\.json$", file_paths))
  has_r <- any(grepl("\\.R$", file_paths))
  has_yaml <- any(grepl("\\.(yml|yaml)$", file_paths))
  has_md <- any(grepl("\\.(md|qmd|rmd|Rmd)$", file_paths))
  has_workflow <- any(grepl("^\\.github/workflows/", file_paths))
  has_data <- any(grepl("^data/", file_paths))
  has_content <- any(grepl("^content/", file_paths))

  sections <- c(sections, paste0(
    "## Review Checklist\n",
    "- [ ] Changes are consistent with the PR description\n",
    "- [ ] No sensitive information (credentials, tokens, emails) is included\n"
  ))

  if (has_json) {
    sections <- c(sections, paste0(
      "### JSON files\n",
      "- [ ] JSON is valid and well-formatted\n",
      "- [ ] File names are lowercase with no special characters\n",
      "- [ ] Required fields are present\n"
    ))
  }

  if (has_r) {
    sections <- c(sections, paste0(
      "### R code\n",
      "- [ ] Functions have roxygen2 documentation\n",
      "- [ ] No hardcoded credentials or paths\n",
      "- [ ] Tests cover new/changed functionality\n"
    ))
  }

  if (has_workflow) {
    sections <- c(sections, paste0(
      "### GitHub Actions workflows\n",
      "- [ ] Secrets are referenced, not hardcoded\n",
      "- [ ] Actions use pinned versions\n",
      "- [ ] Workflow permissions follow least-privilege\n"
    ))
  }

  if (has_content) {
    sections <- c(sections, paste0(
      "### Content\n",
      "- [ ] Spelling and grammar checked\n",
      "- [ ] All links are working\n",
      "- [ ] Images have alt text\n"
    ))
  }

  if (has_data) {
    items <- "- [ ] Data changes are intentional and verified\n"
    if (repo == "directory") {
      items <- paste0(items,
        "- [ ] Social media handles use handles, not full URLs\n",
        "- [ ] Images won't crop to unwanted section\n"
      )
    }
    sections <- c(sections, paste0("### Data\n", items))
  }

  sections <- c(sections, "\n_Generated by jinx_")
  paste(sections, collapse = "\n")
}
