#' Check file naming conventions in a PR
#'
#' Validates that changed files follow repository naming conventions.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param pr_number PR number.
#' @return Data frame with filename and valid columns.
#' @export
check_pr_naming <- function(owner, repo, pr_number) {
  files <- gh::gh(
    "GET /repos/{owner}/{repo}/pulls/{pr_number}/files",
    owner = owner, repo = repo, pr_number = pr_number,
    .limit = Inf
  )

  file_paths <- vapply(files, function(f) f$filename, character(1))
  results <- check_naming_conventions(file_paths, repo)

  violations <- results[!results$valid, ]
  if (nrow(violations) > 0) {
    body <- format_naming_violations(violations)
    gh::gh(
      "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
      owner = owner, repo = repo, issue_number = pr_number,
      body = body
    )
    cli::cli_alert_warning("{nrow(violations)} naming violation{?s} found")
  } else {
    cli::cli_alert_success("All file names follow conventions")
  }

  results
}

check_naming_conventions <- function(file_paths, repo) {
  results <- data.frame(
    filename = file_paths,
    valid = TRUE,
    reason = "",
    stringsAsFactors = FALSE
  )

  for (i in seq_along(file_paths)) {
    path <- file_paths[i]
    basename <- basename(path)
    reasons <- character(0)

    if (grepl("^(data|blogs|contact)/", path) && grepl("\\.json$", path)) {
      if (basename != tolower(basename)) {
        reasons <- c(reasons, "filename must be lowercase")
      }
      if (grepl("[^a-z0-9._-]", sub("\\.json$", "", basename))) {
        reasons <- c(reasons, "filename contains invalid characters")
      }
      if (grepl("^-|-$", sub("\\.json$", "", basename))) {
        reasons <- c(reasons, "filename must not start or end with hyphen")
      }
    }

    if (length(reasons) > 0) {
      results$valid[i] <- FALSE
      results$reason[i] <- paste(reasons, collapse = "; ")
    }
  }

  results
}

format_naming_violations <- function(violations) {
  rows <- vapply(seq_len(nrow(violations)), function(i) {
    glue::glue("| `{violations$filename[i]}` | {violations$reason[i]} |")
  }, character(1))

  paste0(
    "### Naming Convention Issues\n\n",
    "| File | Issue |\n",
    "|------|-------|\n",
    paste(rows, collapse = "\n"),
    "\n\n_Generated by jinx_"
  )
}
