#' Auto-merge PRs with pending label when date matches
#'
#' Checks open PRs with "pending" label in the website repo.
#' If a blog post's date matches today, merges the PR.
#'
#' @param org GitHub organization.
#' @param repo Repository name.
#' @return Character vector of merged PR URLs (invisibly).
#' @export
website_merge_pending <- function(org = "rladies", repo = "rladies.github.io") {
  pending <- review_fetch_pending(org, repo)
  if (length(pending) == 0) {
    cli::cli_alert_info("No pending PRs found")
    return(invisible(character(0)))
  }

  today <- format(Sys.Date(), "%Y-%m-%d")
  merged <- character(0)

  for (pr in pending) {
    if (review_pr_due_today(pr, today, org, repo)) {
      merged <- c(merged, review_try_squash_merge(pr, org, repo))
    }
  }

  invisible(merged)
}

review_fetch_pending <- function(org, repo) {
  prs <- gh::gh(
    "GET /repos/{owner}/{repo}/pulls",
    owner = org,
    repo = repo,
    state = "open",
    .limit = Inf
  )
  Filter(
    function(pr) {
      labels <- vapply(pr$labels, function(l) l$name, character(1))
      "pending" %in% labels && !isTRUE(pr$draft)
    },
    prs
  )
}

review_pr_due_today <- function(pr, today, org, repo) {
  files <- gh::gh(
    "GET /repos/{owner}/{repo}/pulls/{pr_number}/files",
    owner = org,
    repo = repo,
    pr_number = pr$number,
    .limit = Inf
  )
  content_files <- Filter(
    function(f) grepl("^content/.*/index(\\.[a-zA-Z]+)?\\.md$", f$filename),
    files
  )
  if (length(content_files) == 0) {
    return(FALSE)
  }

  for (f in content_files) {
    if (identical(file_yaml_date(f, pr, org, repo), today)) {
      return(TRUE)
    }
  }
  FALSE
}

file_yaml_date <- function(f, pr, org, repo) {
  content <- tryCatch(
    {
      resp <- gh::gh(
        "GET /repos/{owner}/{repo}/contents/{path}",
        owner = org,
        repo = repo,
        path = f$filename,
        ref = pr$head$ref
      )
      rawToChar(jsonlite::base64_dec(resp$content))
    },
    error = function(e) NULL
  )
  if (is.null(content)) NULL else extract_yaml_date(content)
}

review_try_squash_merge <- function(pr, org, repo) {
  tryCatch(
    {
      gh::gh(
        "PUT /repos/{owner}/{repo}/pulls/{pr_number}/merge",
        owner = org,
        repo = repo,
        pr_number = pr$number,
        merge_method = "squash"
      )
      cli::cli_alert_success("Merged PR #{pr$number}: {pr$title}")
      pr$html_url
    },
    error = function(e) {
      cli::cli_alert_danger("Failed to merge PR #{pr$number}: {e$message}")
      review_post_merge_failure(org, repo, pr$number, e$message)
      character(0)
    }
  )
}

#' Post blog PR checklist
#'
#' Posts a review checklist comment on PRs that modify blog content.
#'
#' @param owner Repository owner.
#' @param repo Repository name.
#' @param pr_number PR number.
#' @return Comment URL (invisibly).
#' @export
website_blog_checklist <- function(owner, repo, pr_number) {
  checklist <- paste(
    "Thank you for submitting a blogpost to RLadies+!",
    "",
    "## Content Checklist",
    "- [ ] Ensure the PR is kept as a draft until you are ready for review.",
    "- [ ] Ensure the title is appropriate for publication.",
    "- [ ] Ensure all links are working and point to correct destinations.",
    "- [ ] Ensure internal cross-references (if any) are correct.",
    paste0(
      "- [ ] If the main document is a `qmd` or `rmd`,",
      " make sure the knitted `md` is committed."
    ),
    "- [ ] Ensure no sensitive or confidential information is included.",
    "- [ ] Check grammar and spelling.",
    "- [ ] Ensure all images have alt text `![alt goes here](image.png)`.",
    "",
    "### Review ready",
    paste0(
      "- [ ] Remove draft mode for the PR,",
      " reviewers will be automatically assigned."
    ),
    "",
    "### Reviewers",
    "- [ ] Verify the title is appropriate for publication.",
    "- [ ] Verify all links are working.",
    "- [ ] Verify all images have alt text.",
    paste0(
      "- [ ] If the main document is a `qmd` or `rmd`,",
      " verify the `md` is up to date."
    ),
    "",
    "### Publication",
    '- [ ] Set a date for publication.',
    paste0(
      '- [ ] Change label to "pending" - publication',
      " will happen automatically on that day."
    ),
    "",
    "_Generated by jinx_",
    sep = "\n"
  )

  comment <- gh::gh(
    "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
    owner = owner,
    repo = repo,
    issue_number = pr_number,
    body = checklist
  )

  invisible(comment$html_url)
}

extract_yaml_date <- function(content) {
  lines <- strsplit(content, "\n")[[1]]
  in_yaml <- FALSE
  for (line in lines) {
    if (grepl("^---\\s*$", line)) {
      if (in_yaml) {
        break
      }
      in_yaml <- TRUE
      next
    }
    if (in_yaml && grepl("^date:", line)) {
      date_str <- sub("^date:\\s*", "", line)
      date_str <- gsub("['\"]", "", date_str)
      date_str <- trimws(date_str)
      return(date_str)
    }
  }
  NULL
}

review_post_merge_failure <- function(org, repo, pr_number, reason) {
  body <- glue::glue(
    "The automated merge for this PR failed.\n\n",
    "**Reason**: {reason}\n\n",
    "Please check the workflow logs for details.\n\n",
    "_Generated by jinx_"
  )
  tryCatch(
    gh::gh(
      "POST /repos/{owner}/{repo}/issues/{issue_number}/comments",
      owner = org,
      repo = repo,
      issue_number = pr_number,
      body = body
    ),
    error = function(e) NULL
  )
}
